FROM python:3.10-slim
WORKDIR /app

# Instala dependencias
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia código y artefactos del modelo
COPY api/ api/
COPY models/model.pkl models/columnas_modelo.pkl models/

EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
